// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knaqfnuxrhmgsxywqlxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYXFmbnV4cmhtZ3N4eXdxbHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNzczNDgsImV4cCI6MjA1Mzc1MzM0OH0.W_qhR7LvSjuelYMQkmMmF2KEhC5-6_aJr5FMwC3Bpvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);